# Site Settings
title: Mathieu Lagüe | Startup your business
email: mathieu@lague.me
description: Je suis Mathieu Lagüe et je peux vous aider à démarrer votre
 business, créer un produit ou service et l'amener jusqu'au "product/market fit"
 en passant par le "problem/solution fit"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mathieu.lague.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Mathieu Lagüe
user_description: En suivant les principes du Lean Startup nous partirons du
 problem/solution fit pour avoir les données nécessaires sur l'environnement et
 les problèmes rencontrés par vos utilisateurs. Une fois ces métrics en main
 nous réflechirons et itérerons ensemble pour arriver au product/market fit.
 En bref je suis votre cofondateur par interim.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: m-lague
facebook_username: facebook_username
twitter_username: MathieuLAGUE
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
    external: true
  - title: Contact
    url: /contact/
  - title: Portfolio
    url: /portofolio/


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
